version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      timezone: 'UTC'
      time: '10:00'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    target-branch: 'dev'
    pull-request-branch-name:
      separator: '/'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      timezone: 'UTC'
      time: '10:00'
    labels:
      - 'dependencies'
    versioning-strategy: auto
    open-pull-requests-limit: 5
    target-branch: 'dev'
    pull-request-branch-name:
      separator: '/'
    # Only allow security updates
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch', 'version-update:semver-minor', 'version-update:semver-major']
