name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

# Default permissions for all jobs (can be overridden per job)
permissions:
  contents: read

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - run: |
          npm install
      - run: |
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          title: Check pk only check
          branch: dev
          notify_issue: false
          notify_check: true
          report_public_keys: true
          token: ${{ secrets.GITHUB_TOKEN }}

  testOnlyNotify: # make sure the action only notifies without failing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          title: Check pk only notify
          branch: dev
          only_notify: true
          report_public_keys: true
          token: ${{ secrets.GITHUB_TOKEN }}
